### PR TITLE
New wavelengths specified can fall outside the range of the old wavelength values

### PR DESCRIPTION
**Pull request by cylammarco**
### New acceptable `new_spec_wavs`
spectres now only requires an overlapping wavelength range between the `old_spec_wavs` and `new_spec_wavs`, it gives a warning in such cases. The original `ValueError` would be triggered if the `new_spec_wavs` is completely outside the range of `old_spec_wavs`.

### Performance
A dummy array for `spec_widths_ranged` is used, so`start_factor` and `end_factor` are only used once. Simple timing test shows a small performance gain.

### Jupyter Notebook
A Jupyter notebook `example_hizquasar.ipynb` is created such that the `example_hizquasar.py` can be viewed on GitHub. Vertical offsets are applied to the plot.

### Formatted with yapf
The default setting of yapf is used to format the script

### CODE REVIEW

**Comment by cylammarco** [comment]
For the cases with `new_spec_wavs` outside the range of `old_spec_wavs`, the total flux of the spectrum is not conserved, need to do something about the bins at the edge.

**Comment by ACCarnall** [comment]
Hey Marco, I've had a look through your proposed changes and I have a few concerns, in particular:

 - Your "spec_widths_ranged" approach leads to permanent modification of the spec_widths array at each step in the loop, as sections of it are passed by reference into spec_widths_ranged. This causes the results to be incorrect for all but the first new wavelength bin.

 - Your use of "rhs" arrays removes the ability of the code to deal with non-uniform wavelength sampling, which will cause errors in people's results without throwing an error (see lines 77 and 78 in your updated version).

I agree with the basic aim of the pull request, the current inability of the code to deal with new wavelength ranges outside the old wavelength range is very frustrating. However, I think that this can be fixed a.) without modifying the core algorithm, and b.) in a way that provides an interface that is as similar as possible to numpy functions for interpolation.

As this code seems to now be in fairly widespread use, and reliably does the core job for which it was designed, I'm reluctant to make any unnecessary changes that might introduce bugs. I'll do my best to get around to adding this feature, but I can't promise I'll get to it straight away.

**Comment by ACCarnall** [comment]
Hey Marco, I just pushed some changes to the repository, perhaps you could take a look and see if this now does what you want?

**Comment by cylammarco** [comment]
> * Your "spec_widths_ranged" approach leads to permanent modification of the spec_widths array at each step in the loop, as sections of it are passed by reference into spec_widths_ranged. This causes the results to be incorrect for all but the first new wavelength bin.

This is not meant to change your approach, but merely a bug introduced, I should have kept the same divisions like in:
https://github.com/ACCarnall/SpectRes/blob/227e72f383907b5ebb38a11045fe23547dc91cc1/spectres/spectral_resampling.py#L143-144

However, this can also be resolved by changing from
https://github.com/cylammarco/SpectRes/blob/15bd13e822dbeac108b311376d9963a6c37e68da/spectres/spectral_resampling.py#L152
to
```
spec_widths_ranged = spec_widths[start:stop + 1].copy()
```
The reason for introducing it is for readability, though the choice of name is not the best, on
https://github.com/cylammarco/SpectRes/blob/15bd13e822dbeac108b311376d9963a6c37e68da/spectres/spectral_resampling.py#L132
but it is certainly not a necessary change.

> * Your use of "rhs" arrays removes the ability of the code to deal with non-uniform wavelength sampling, which will cause errors in people's results without throwing an error (see lines 77 and 78 in your updated version).

This is also not meant to change your approach, this is another bug... these 2 lines https://github.com/cylammarco/SpectRes/blob/15bd13e822dbeac108b311376d9963a6c37e68da/spectres/spectral_resampling.py#L77-78
should be 
```
spec_rhs = spec_lhs + spec_widths
filter_rhs = filter_lhs + filter_widths
```
The use of the RHS is not meant to do any change to the core code as well but was to make it easier to handle indices. For example, on your current master, when I try it with my spectrum it throws this error:

> /usr/local/lib/python3.7/site-packages/spectres/spectral_resampling.py in spectres(new_wavs, spec_wavs, spec_fluxes, spec_errs, fill)
>     105 
>     106         # Find first old bin which is partially covered by the new bin
> --> 107         while old_lhs[start+1] <= new_lhs[j]:
>     108             start += 1
>     109 
> 
> IndexError: index 2540 is out of bounds for axis 0 with size 2540
> 

I think this is caused by the old_lhs[start+1] not being trapped when the new spectral wavelength range extends beyond the old maximum wavelength range.

**Comment by cylammarco** [comment]
The ```silence``` parameter is a lazy implementation of setting verbosity to all or nothing. It is not a necessary change either.

**Comment by cylammarco** [comment]
### Start/Stop Indices
In the new master in v2.1.0, there are problems with the start/stop indices in some cases when the `start` and `stop` become larger than or equal to `old_wavs.shape[0]`. If statements are added in my latest master based on your new master to trap these cases.

```
        # Find first old bin which is partially covered by the new bin
        while old_lhs[start+1] <= new_lhs[j]:
            start += 1
            if start == old_wavs.shape[0] - 1:
                break

        # Find last old bin which is partially covered by the new bin
        while old_lhs[stop+1] < new_lhs[j+1]:
            stop += 1
            if stop == old_wavs.shape[0] - 1:
                break
```

Same thing happens when computing the `start_factor` and `end_factor` when `stop+1` is used as an index. From my understanding to the code, I believer this is be resolved by using `old_widths[stop]`.

```
        # Otherwise multiply the first and last old bin widths by P_ij
        else:
            start_factor = ((old_lhs[start+1] - new_lhs[j])
                            / (old_widths[start]))

            end_factor = ((new_lhs[j+1] - old_lhs[stop])
                          / (old_widths[stop]))

            old_widths[start] *= start_factor
            old_widths[stop] *= end_factor
```

**Comment by ACCarnall** [comment]
This is getting very confusing now. I'm going to close this pull request as the original aim has already been fulfilled. 

If you'd like to please submit a new pull request that makes the minimal changes necessary to fix the bug you're talking about, including a minimum example to demonstrate the problem with the current version.

I'm happy to consider other changes as well, but please make sure they are necessary, keep them separate and provide a clear description of what is being changed and why.

**Pull request closed without merging**
